#!/usr/bin/env bash
# installs nginx and configures it on a remote hosting server
#Installation conducted by apt package manager
#may require root privilleges

apt-get -y update
apt-get -y install nginx
ufw allow '30.198.248.145'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
