#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th time, displays "Hi" before string "Best School".

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
done
